name: municipal_rental_tc_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.4
  get_storage: ^2.1.1
  geolocator: ^8.2.0
  permission_handler: ^9.2.0
  image_picker: ^0.8.5
  image_cropper: ^3.0.1
  flutter_image_compress: ^1.1.3
  print_bluetooth_thermal: ^1.0.5
  esc_pos_utils_plus: ^2.0.1+6
  dropdown_button2: ^2.1.4
  flutter_spinkit: ^5.2.0
  datetime_picker_formfield: ^2.0.1
  intl: ^0.18.0
  flutter_pinelabs: ^1.1.0+3
  awesome_dialog: ^3.0.2




dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/images/

  uses-material-design: true

